(in-package #:cl-ggplot2)

(defun %aes-slot-name (aes-key)
  (case aes-key
    (:x 'x)
    (:y 'y)
    (:color 'color)
    (:fill 'fill)
    (:size 'size)
    (:shape 'shape)
    (:alpha 'alpha)
    (:group 'group)
    (:linetype 'linetype)
    (:xmin 'xmin)
    (:xmax 'xmax)
    (:ymin 'ymin)
    (:ymax 'ymax)
    (:middle 'middle)
    (:lower 'lower)
    (:upper 'upper)
    (:label 'label)
    (:xend 'xend)
    (:yend 'yend)
    (t aes-key)))

(defun %split-data-facet-wrap (data facet-var)
  "Splits a tibble for facet_wrap."
  (if (not facet-var)
      (list (list :value :default :data data))
      (let* ((col-name (if (keywordp facet-var) (string-downcase (string facet-var)) facet-var))
             (vals (cl-tibble:tbl-col data col-name))
             (unique-vals (remove-duplicates (coerce vals 'list) :test #'equal))
             (result nil))
        (dolist (uv unique-vals)
          (let ((indices (loop for i from 0 below (length vals)
                               when (equal (aref vals i) uv)
                               collect i)))
            (push (list :value uv :data (cl-tibble:slice data :rows indices)) result)))
        (nreverse result))))

(defun %split-data-facet-grid (data rows-var cols-var)
  "Splits a tibble for facet_grid."
  (let* ((row-col (when rows-var (if (keywordp rows-var) (string-downcase (string rows-var)) rows-var)))
         (col-col (when cols-var (if (keywordp cols-var) (string-downcase (string cols-var)) cols-var)))
         (row-vals (when row-col (cl-tibble:tbl-col data row-col)))
         (col-vals (when col-col (cl-tibble:tbl-col data col-col)))
         (n (cond (row-vals (length row-vals))
                  (col-vals (length col-vals))
                  (t 0))))
    (unless row-vals (setf row-vals (make-array n :initial-element :default)))
    (unless col-vals (setf col-vals (make-array n :initial-element :default)))
    (let* ((unique-rows (remove-duplicates (coerce row-vals 'list) :test #'equal))
           (unique-cols (remove-duplicates (coerce col-vals 'list) :test #'equal))
           (result nil))
      (loop for rv in unique-rows
            for r-idx from 0
            do (loop for cv in unique-cols
                     for c-idx from 0
                     do (let ((indices (loop for i from 0 below (length row-vals)
                                             when (and (equal (aref row-vals i) rv)
                                                       (equal (aref col-vals i) cv))
                                             collect i)))
                          (when indices
                            (push (list :value (list rv cv) :data (cl-tibble:slice data :rows indices)
                                        :row r-idx :col c-idx :row-val rv :col-val cv) result)))))
      (values (nreverse result) (length unique-rows) (length unique-cols)))))

(defun %get-legend-data (scales)
  "Extracts legend info from non-XY scales."
  (let ((legends nil))
    (dolist (c '(:color :fill :size :shape :alpha))
      (let ((s (gethash c scales)))
        (when (and s (scale-guide s))
          (let ((breaks (scale-breaks s)))
            (when (and breaks (> (length breaks) 0))
              (let ((items nil))
                (dolist (b breaks)
                  (let ((val (scale-map s (vector b) 0 1)))
                    (push (list :label (format nil "~a" b) :value (aref val 0)) items)))
                (push (list :channel c :title (or (scale-name s) (string-capitalize (string c))) :items (nreverse items)) legends)))))))
    (nreverse legends)))

(defun build-plot (plot width height)
  "Bridges the gap between plot specification and rendering instructions."
  (let* ((data (plot-data plot))
         (layers (plot-layers plot))
         (facet (plot-facet plot))
         (coord (or (plot-coord plot) (coord_cartesian)))
         (margin 50)
         (global-scales (or (plot-scales plot) (setf (plot-scales plot) (make-hash-table))))
         (facet-scales (if facet (facet-scales facet) :fixed)))

    (dolist (c '(:x :y))
      (unless (gethash c global-scales)
        (setf (gethash c global-scales) (make-instance 'scale-continuous :channel c))))

    (multiple-value-bind (panel-objects nrow ncol)
        (cond
          ((and (typep facet 'facet-wrap) data)
           (let* ((objs (%split-data-facet-wrap data (facet-facets facet)))
                  (n (length objs))
                  (nc (or (facet-ncol facet) (ceiling (sqrt n)) 1))
                  (nr (max 1 (ceiling n nc)))
                  (indexed-objs (loop for o in objs for i from 0
                                      collect (append (list :row (floor i nc) :col (mod i nc)) o))))
             (values (or indexed-objs (list (list :value :default :data data :row 0 :col 0))) nr nc)))
          ((and (typep facet 'facet-grid) data)
           (multiple-value-bind (objs nr nc)
               (%split-data-facet-grid data (facet-rows facet) (facet-cols facet))
             (values (or objs (list (list :value :default :data data :row 0 :col 0))) (max 1 nr) (max 1 nc))))
          (t (values (list (list :value :default :data data :row 0 :col 0)) 1 1)))

      (let* ((legend-width 120)
             (plotting-width (- width margin margin legend-width))
             (panel-width (/ plotting-width ncol))
             (panel-height (/ (- height (* 2 margin)) nrow))
             (built-panels nil))

        (setf panel-objects
              (loop for p in panel-objects
                    collect (let ((p-scales (make-hash-table)))
                              (maphash (lambda (k s)
                                         (let ((free (case facet-scales
                                                       (:free t)
                                                       (:free_x (eq k :x))
                                                       (:free_y (eq k :y))
                                                       (t nil))))
                                           (setf (gethash k p-scales) (if free (scale-clone s) s))))
                                       global-scales)
                              (append (list :scales p-scales) p))))

        (setf panel-objects
              (loop for p in panel-objects
                    collect (let ((p-tibble (getf p :data))
                                  (p-scales (getf p :scales))
                                  (p-layers nil))
                              (dolist (l layers)
                                (let* ((l-data (or (layer-data l) p-tibble))
                                       (l-mapping (or (layer-mapping l) (plot-mapping plot)))
                                       (l-stat (layer-stat l)))
                                  (multiple-value-bind (transformed-data changed-aes)
                                      (stat-compute l-stat l-data l-mapping (layer-params l))
                                    (let ((final-mapping (make-instance 'mapping)))
                                      (dolist (slot '(x y color fill size shape alpha group linetype xmin xmax ymin ymax middle lower upper label xend yend))
                                        (setf (slot-value final-mapping slot) (slot-value l-mapping slot)))
                                      (loop for (aes-key col-name) on changed-aes by #'cddr
                                            do (setf (slot-value final-mapping (%aes-slot-name aes-key)) col-name))
                                      
                                      (let* ((pos-attr (layer-position l))
                                             (pos (cond ((eq pos-attr :identity) (position_identity))
                                                        ((eq pos-attr :stack) (position_stack))
                                                        ((eq pos-attr :dodge) (position_dodge))
                                                        ((eq pos-attr :fill) (position_fill))
                                                        ((typep pos-attr 'position-adj) pos-attr)
                                                        (t (position_identity))))
                                             (pos-data (make-hash-table)))
                                        (dolist (c '(:x :y :group :color :fill :xmin :xmax :ymin :ymax :xend :yend))
                                          (let* ((selector (slot-value final-mapping (%aes-slot-name c)))
                                                 (constant (getf (layer-params l) c)))
                                            (if constant
                                                (setf (gethash c pos-data) constant)
                                                (when selector
                                                  (let ((col-name (if (keywordp selector) (string-downcase (string selector)) selector)))
                                                    (setf (gethash c pos-data) (cl-tibble:tbl-col transformed-data col-name)))))))
                                        (position-adjust pos pos-data (layer-params l))

                                        (dolist (channel '(:x :y :color :fill :size :alpha :shape :linetype :xmin :xmax :ymin :ymax :middle :lower :upper :label :xend :yend))
                                          (let* ((cs-key (case channel
                                                           ((:xmin :xmax :xend) :x)
                                                           ((:ymin :ymax :middle :lower :upper :yend) :y)
                                                           (t channel)))
                                                 (col-selector (slot-value final-mapping (%aes-slot-name channel)))
                                                 (constant-override (getf (layer-params l) channel))
                                                 (pos-val (gethash channel pos-data))
                                                 (scale (gethash cs-key p-scales)))
                                            (let ((values (cond
                                                            ((and (member channel '(:x :y))
                                                                  (or (gethash :xmin pos-data) (gethash :ymin pos-data)))
                                                             nil)
                                                            ((and (member channel '(:x :y :xmin :xmax :ymin :ymax)) pos-val)
                                                             (if (or (not (typep pos-val 'sequence)) (stringp pos-val))
                                                                 (vector pos-val)
                                                                 pos-val))
                                                            ((and col-selector (not constant-override))
                                                             (let ((col-name (if (keywordp col-selector) (string-downcase (string col-selector)) col-selector)))
                                                               (cl-tibble:tbl-col transformed-data col-name)))
                                                            (t nil))))
                                              (when (and values (> (length values) 0))
                                                (unless scale
                                                  (setf scale
                                                        (case cs-key
                                                          (:color (make-instance 'scale-color-discrete :channel :color))
                                                          (:fill (make-instance 'scale-fill-discrete :channel :fill))
                                                          (:size (make-instance 'scale-size-continuous :channel :size))
                                                          (:alpha (make-instance 'scale-alpha-continuous :channel :alpha))
                                                          (:shape (make-instance 'scale-shape-discrete :channel :shape))
                                                          (t (make-instance 'scale-continuous :channel cs-key))))
                                                  (setf (gethash cs-key p-scales) scale)
                                                  (unless (case facet-scales
                                                            (:free t) (:free_x (eq cs-key :x)) (:free_y (eq cs-key :y)) (t nil))
                                                    (setf (gethash cs-key global-scales) scale)))
                                                
                                                (when (and (not (typep scale 'scale-discrete))
                                                           (loop for i from 0 below (min 10 (length values))
                                                                 for v = (aref values i)
                                                                 thereis (not (or (cl-vctrs-lite:na-p v) (numberp v)))))
                                                  (let ((new-scale (case cs-key
                                                                     (:color (make-instance 'scale-color-discrete :channel :color))
                                                                     (:fill (make-instance 'scale-fill-discrete :channel :fill))
                                                                     (:shape (make-instance 'scale-shape-discrete :channel :shape))
                                                                     (t (make-instance 'scale-discrete :channel cs-key)))))
                                                    (setf (gethash cs-key p-scales) new-scale)
                                                    (unless (case facet-scales
                                                              (:free t) (:free_x (eq cs-key :x)) (:free_y (eq cs-key :y)) (t nil))
                                                      (setf (gethash cs-key global-scales) new-scale))
                                                    (setf scale new-scale)))
                                                (scale-train scale values)))))
                                      
                                      (push (list :layer l :data transformed-data :pos-data pos-data :mapping final-mapping) p-layers))))))
                              (append (list :p-layers (nreverse p-layers)) p))))

        (setf built-panels
              (loop for p in panel-objects
                    collect
                    (let* ((p-row (getf p :row))
                           (p-col (getf p :col))
                           (p-x (+ margin (* p-col panel-width)))
                           (p-y (+ margin (* p-row panel-height)))
                           (p-scales (getf p :scales))
                           (coord-map (coord-map-scales coord p-scales p-x p-y panel-width panel-height))
                           (x-range (getf coord-map :x-range))
                           (y-range (getf coord-map :y-range))
                           (mapped-layers
                             (loop for pl in (getf p :p-layers)
                                   collect
                                   (let* ((l (getf pl :layer))
                                          (l-data (getf pl :data))
                                          (l-pos-data (getf pl :pos-data))
                                          (l-mapping (getf pl :mapping))
                                          (mapped-data (make-hash-table)))
                                     (dolist (c '(:x :y :color :fill :size :alpha :shape :linetype :xmin :xmax :ymin :ymax :middle :lower :upper :label :xend :yend))
                                       (let ((selector (slot-value l-mapping (%aes-slot-name c)))
                                             (constant (getf (layer-params l) c))
                                             (pos-val (gethash c l-pos-data)))
                                         (cond 
                                           ((and (member c '(:x :y :xmin :xmax :ymin :ymax :xend :yend)) pos-val)
                                            (let* ((scale (gethash (case c ((:xmin :xmax :xend) :x)
                                                                           ((:ymin :ymax :middle :lower :upper :yend) :y)
                                                                           (t c)) p-scales))
                                                   (vals (if (or (not (typep pos-val 'sequence)) (stringp pos-val))
                                                             (vector pos-val)
                                                             pos-val)))
                                              (setf (gethash c mapped-data)
                                                    (case c
                                                      ((:x :xmin :xmax :xend) (scale-map scale vals (first x-range) (second x-range)))
                                                      ((:y :ymin :ymax :middle :lower :upper :yend) (scale-map scale vals (first y-range) (second y-range)))
                                                      (t (scale-map scale vals 0 1))))))
                                           (constant (setf (gethash c mapped-data) constant))
                                           (selector
                                            (let* ((col-name (if (keywordp selector) (string-downcase (string selector)) selector))
                                                   (vals (cl-tibble:tbl-col l-data col-name))
                                                   (scale (gethash (case c ((:xmin :xmax :xend) :x)
                                                                           ((:ymin :ymax :middle :lower :upper :yend) :y)
                                                                           (t c)) p-scales)))
                                              (setf (gethash c mapped-data)
                                                    (case c
                                                      ((:x :xmin :xmax :xend) (scale-map scale vals (first x-range) (second x-range)))
                                                      ((:y :ymin :ymax :middle :lower :upper :yend) (scale-map scale vals (first y-range) (second y-range)))
                                                      (t (scale-map scale vals 0 1))))))
                                           (t nil))))
                                     (list :layer l :data (coord-transform-mapped coord mapped-data))))))
                      (list :value (getf p :value) :x p-x :y p-y :width panel-width :height panel-height 
                            :layers mapped-layers :scales p-scales))))

        (list :panels built-panels :scales global-scales :ncol ncol :nrow nrow :panel-width panel-width :panel-height panel-height
              :legends (%get-legend-data global-scales))))))

(defun %draw-labels (plot renderer width height margin)
  (declare (ignore margin))
  (let ((title (plot-title plot))
        (subtitle (plot-subtitle plot))
        (x-lab (plot-x-label plot))
        (y-lab (plot-y-label plot))
        (theme (or (plot-theme plot) (make-instance 'theme))))
    (r-set-style renderer :fill (theme-axis-text-color theme))
    (when title
      (r-text renderer (/ width 2) 20 title :anchor "middle" :font-size 16))
    (when subtitle
      (r-text renderer (/ width 2) 40 subtitle :anchor "middle" :font-size 12))
    (when x-lab
      (r-text renderer (/ width 2) (- height 10) x-lab :anchor "middle" :font-size 12))
    (when y-lab
      (r-set-style renderer :fill (theme-axis-text-color theme))
      (r-text renderer 15 (/ height 2) y-lab :anchor "middle" :font-size 12 :angle -90))))

(defun draw-panel-skeleton (plot renderer p-info theme built-scales)
  "Draws background and grids for a single panel."
  (let* ((p-x (getf p-info :x))
         (p-y (getf p-info :y))
         (p-w (getf p-info :width))
         (p-h (getf p-info :height))
         (p-val (getf p-info :value))
         (coord (or (plot-coord plot) (coord_cartesian)))
         (x-scale (gethash :x built-scales))
         (y-scale (gethash :y built-scales))
         (coord-map (coord-map-scales coord built-scales p-x p-y p-w p-h))
         (x-range (getf coord-map :x-range))
         (y-range (getf coord-map :y-range)))
    (r-set-style renderer :fill (theme-panel-fill theme) :stroke (theme-panel-stroke theme) :stroke-width 1)
    (r-rect renderer p-x p-y p-w p-h)
    
    (when (not (eq p-val :default))
      (r-set-style renderer :fill "#eeeeee" :stroke (theme-panel-stroke theme) :stroke-width 1)
      (r-rect renderer p-x p-y p-w 20)
      (r-set-style renderer :fill (theme-axis-text-color theme))
      (r-text renderer (+ p-x (/ p-w 2)) (+ p-y 15) (format nil "~a" p-val) :anchor "middle" :font-size 10))

    (when y-scale
      (let ((breaks (scale-breaks y-scale)))
        (dolist (b breaks)
          (let ((y (scale-map y-scale (vector b) (first y-range) (second y-range))))
            (setf y (aref y 0))
            (r-set-style renderer :stroke (theme-grid-color theme) :stroke-width 1)
            (if (typep coord 'coord-flip)
                (r-line renderer y p-y y (+ p-y p-h))
                (r-line renderer p-x y (+ p-x p-w) y))
            (unless (typep coord 'coord-flip)
              (when (<= (abs (- p-x 50)) 2)
                (r-set-style renderer :stroke (theme-axis-tick-color theme) :stroke-width 1)
                (r-line renderer (- p-x 5) y p-x y)
                (r-set-style renderer :fill (theme-axis-text-color theme))
                (r-text renderer (- p-x 10) y (format nil "~a" b) :anchor "end" :font-size (theme-axis-text-size theme))))))))

    (when x-scale
      (let ((breaks (scale-breaks x-scale)))
        (dolist (b breaks)
          (let ((x (scale-map x-scale (vector b) (first x-range) (second x-range))))
            (setf x (aref x 0))
            (r-set-style renderer :stroke (theme-grid-color theme) :stroke-width 1)
            (if (typep coord 'coord-flip)
                (r-line renderer p-x x (+ p-x p-w) x)
                (r-line renderer x p-y x (+ p-y p-h)))
            (unless (typep coord 'coord-flip)
              (r-set-style renderer :stroke (theme-axis-tick-color theme) :stroke-width 1)
              (r-line renderer x (+ p-y p-h) x (+ p-y p-h 5))
              (r-set-style renderer :fill (theme-axis-text-color theme))
              (r-text renderer x (+ p-y p-h 15) (format nil "~a" b) :anchor "middle" :font-size (theme-axis-text-size theme)))))))

    (r-set-style renderer :stroke (theme-axis-line-color theme) :stroke-width 1)
    (r-line renderer p-x (+ p-y p-h) (+ p-x p-w) (+ p-y p-h))
    (r-line renderer p-x p-y p-x (+ p-y p-h))))

(defun %draw-legends (legends renderer width height theme)
  "Draws legends on the right."
  (declare (ignore height))
  (let ((x (- width 100))
        (y 80)
        (item-height 20))
    (dolist (leg legends)
      (r-set-style renderer :fill (theme-axis-text-color theme))
      (r-text renderer x y (getf leg :title) :font-size 12 :font-weight "bold")
      (incf y 15)
      (dolist (item (getf leg :items))
        (let ((chan (getf leg :channel))
              (val (getf item :value)))
          (case chan
            ((:color :fill)
             (r-set-style renderer :fill val :stroke "none")
             (r-rect renderer x y 12 12))
            (:size
             (r-set-style renderer :fill "#333" :stroke "none")
             (r-circle renderer (+ x 6) (+ y 6) val))
            (:alpha
             (r-set-style renderer :fill "#333" :stroke "none" :opacity val)
             (r-rect renderer x y 12 12))
            (:shape
             (r-set-style renderer :fill "#333" :stroke "none")
             (r-circle renderer (+ x 6) (+ y 6) 3)))
          (r-set-style renderer :fill (theme-axis-text-color theme))
          (r-text renderer (+ x 20) (+ y 10) (getf item :label) :font-size 10)
          (incf y item-height)))
      (incf y 20))))

(defun render (plot &key (device :svg) (width 600) (height 400) (dpi 96))
  (declare (ignore dpi))
  (let* ((renderer (ecase device
                     (:svg (make-instance 'svg-renderer))))
         (built (build-plot plot width height))
         (panels (getf built :panels))
         (legends (getf built :legends))
         (theme (or (plot-theme plot) (make-instance 'theme)))
         (margin 50))
    
    (r-begin renderer width height)
    (r-set-style renderer :fill "white" :stroke "none")
    (r-rect renderer 0 0 width height)
    
    (%draw-labels plot renderer width height margin)
    
    (dolist (p-info panels)
      (let ((p-scales (getf p-info :scales)))
        (draw-panel-skeleton plot renderer p-info theme p-scales)
        (dolist (l-info (getf p-info :layers))
          (let ((geom (layer-geom (getf l-info :layer)))
                (data (getf l-info :data)))
            (geom-draw geom data renderer)))))
    
    (%draw-legends legends renderer width height theme)
    
    (r-end renderer)))

(defun save (plot filename &key (width 600) (height 400) (device :svg))
  (let ((output (render plot :device device :width width :height height)))
    (with-open-file (out filename :direction :output :if-exists :supersede :external-format :utf-8)
      (write-string output out))
    filename))
