(in-package #:cl-ggplot2)

(defclass mapping ()
  ((x :initarg :x :initform nil :accessor aes-x)
   (y :initarg :y :initform nil :accessor aes-y)
   (color :initarg :color :initform nil :accessor aes-color)
   (fill :initarg :fill :initform nil :accessor aes-fill)
   (size :initarg :size :initform nil :accessor aes-size)
   (shape :initarg :shape :initform nil :accessor aes-shape)
   (alpha :initarg :alpha :initform nil :accessor aes-alpha)
   (group :initarg :group :initform nil :accessor aes-group)
   (linetype :initarg :linetype :initform nil :accessor aes-linetype)))

(defclass layer ()
  ((geom :initarg :geom :accessor layer-geom)
   (stat :initarg :stat :accessor layer-stat)
   (position :initarg :position :initform :identity :accessor layer-position)
   (data :initarg :data :initform nil :accessor layer-data)
   (mapping :initarg :mapping :initform nil :accessor layer-mapping)
   (params :initarg :params :initform nil :accessor layer-params)))

(defclass plot ()
  ((data :initarg :data :accessor plot-data)
   (mapping :initarg :mapping :initform nil :accessor plot-mapping)
   (layers :initarg :layers :initform (list) :accessor plot-layers)
   (theme :initarg :theme :initform nil :accessor plot-theme)
   (coord :initarg :coord :initform nil :accessor plot-coord)
   (title :initarg :title :initform nil :accessor plot-title)
   (subtitle :initarg :subtitle :initform nil :accessor plot-subtitle)
   (x-label :initarg :x-label :initform nil :accessor plot-x-label)
   (y-label :initarg :y-label :initform nil :accessor plot-y-label)
   (labels :initarg :labels :initform (list) :accessor plot-labels)))

(defun ggplot (data &optional mapping)
  (make-instance 'plot :data data :mapping mapping))
